spring:
  cloud:
    config:
      allowOverride: true
  data:
    mongodb:
      username: root
      password: rootpassword
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090